languageCode = "en"
languageName = "English"
weight = 1
title = "CATNAP CORNER｜數位生活休憩地"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  logo = "img/favicon-64x64.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "網路漫遊貓"
  image = "img/avatar.png"
  headline = "分享網路好用的東西，善用工具避免分頁爆炸。<br>Tools. Tips. Tiny naps.<br>/ᐠ – ˕ -マ Ⳋ"
  bio = "Tab Overflow Crisis Manager"